#!/bin/bash
crontab -l > lalala
echo "@midnight \
	C1=\"\$(md5sum /etc/crontab | awk '{ print \ $1 }')\" && \
	C2=\"\$(cat /etc/crontab.log)\" && \
	if [ '\$C1' != '$\C2'] ; then \
		md5sum /etc/crontab | awk '{ print \$1 }' > /etc/crontab.log && \
		mail -s '/etc/crontab modified' root ; fi" >> lalala
crontab lalala
rm lalala